// ─────────────────────────────────────────────────────────────
//  Guides — short, first-hand fixes for the problems AI-built apps hit.
//
//  Why they exist: a one-week-old domain can't rank for "hire a developer",
//  but it can rank for a specific error message, and a specific, correct
//  answer is what AI assistants cite. Each guide solves one problem
//  completely and then points at the service that fixes the rest
//  (`service` is a slug from constants/services.js).
//
//  Every command and config here must be something that works as written.
//  Text blocks support `inline code` in backticks; nothing else is parsed.
//
//  Plain data with no imports, so vite.config.js can read it in Node.
// ─────────────────────────────────────────────────────────────

export const guides = [
  {
    slug: "supabase-rls-disabled-in-public",
    title: "Supabase says “RLS disabled in public”: what it means and how to fix it",
    seoTitle: "Supabase “RLS Disabled in Public”: How to Fix It · Sameem Amjad",
    seoDescription:
      "Supabase warns RLS is disabled on a public table? Here's what anyone with your anon key can do until you fix it, and the SQL to enable RLS and write policies.",
    summary:
      "What the warning means, what's exposed until you fix it, and the SQL to turn row-level security on and write policies that hold.",
    published: "2026-09-29",
    updated: "2026-09-29",
    service: "fix-vibe-coded-app",
    sections: [
      {
        h2: "The short answer",
        blocks: [
          {
            p: "The warning means a table in your `public` schema can be read and changed by anyone who has your project's anon key. The anon key is in your app's JavaScript, so that means anyone who opens your site. Turn row-level security (RLS) on for the table, then add policies that say exactly who may read and write which rows.",
          },
        ],
      },
      {
        h2: "Why it matters",
        blocks: [
          {
            p: "Supabase exposes the tables in your `public` schema through an auto-generated REST API. Your front end calls that API with the anon key, which is public by design: it ships to every visitor's browser. Row-level security is what stops that key from being a master key. With RLS off, a request like this returns every row in the table, and similar requests can change or delete them:",
          },
          {
            code: `curl 'https://YOUR-PROJECT.supabase.co/rest/v1/profiles?select=*' \\
  -H "apikey: YOUR_ANON_KEY" \\
  -H "Authorization: Bearer YOUR_ANON_KEY"`,
            lang: "bash",
          },
          {
            p: "This is the most common serious problem in apps built with AI tools. In 2025 it got its own CVE (CVE-2025-48757) after security researchers found apps generated by Lovable leaving tables open this way.",
          },
        ],
      },
      {
        h2: "Step 1: turn RLS on",
        blocks: [
          { p: "In the SQL editor, enable RLS on every table the warning lists:" },
          { code: "alter table public.profiles enable row level security;", lang: "sql" },
          {
            p: "You can also do it in the dashboard: Table Editor, open the table, enable RLS. Once RLS is on and the table has no policies, the `anon` and `authenticated` roles can't see any rows. Reads return an empty array rather than an error, so your app will look empty until you add policies. The `service_role` key bypasses RLS entirely, which is why it must never be in front-end code.",
          },
        ],
      },
      {
        h2: "Step 2: add policies for who can do what",
        blocks: [
          {
            p: "Policies are SQL rules attached to a table. `using` decides which existing rows a user can see, update or delete; `with check` decides which new or changed rows they may write. For a table where each user owns their own rows:",
          },
          {
            code: `-- Signed-in users can read their own profile
create policy "Users can read their own profile"
on public.profiles for select
to authenticated
using ( (select auth.uid()) = user_id );

-- Users can create a profile only for themselves
create policy "Users can create their own profile"
on public.profiles for insert
to authenticated
with check ( (select auth.uid()) = user_id );

-- Users can update only their own profile, and can't hand it to someone else
create policy "Users can update their own profile"
on public.profiles for update
to authenticated
using ( (select auth.uid()) = user_id )
with check ( (select auth.uid()) = user_id );`,
            lang: "sql",
          },
          {
            p: "If some data really is public, say so explicitly. A products table everyone can read, with no write policy, so only your server can change it:",
          },
          {
            code: `create policy "Products are readable by everyone"
on public.products for select
to anon, authenticated
using ( true );`,
            lang: "sql",
          },
          {
            p: "Policies filter rows; they don't grant access to the table itself. On Supabase projects created since 30 May 2026, and on all projects from 30 October 2026, new tables in `public` no longer get default privileges for `anon` and `authenticated`. If a request fails with `permission denied` (error 42501) instead of returning rows, grant the table the access your policies describe:",
          },
          {
            code: `grant select on public.products to anon, authenticated;
grant select, insert, update on public.profiles to authenticated;`,
            lang: "sql",
          },
          {
            p: "Two details matter for speed. Wrapping `auth.uid()` in a `select`, as above, lets Postgres evaluate it once per query instead of once per row, which is what Supabase recommends. And the column you compare against should be indexed:",
          },
          { code: "create index on public.profiles (user_id);", lang: "sql" },
        ],
      },
      {
        h2: "Step 3: check the places RLS doesn't cover",
        blocks: [
          {
            list: [
              "Views. A view runs with its owner's permissions by default, so it can skip the table's RLS. Create views with `security_invoker = true` (Postgres 15 and later) so they respect the caller's policies.",
              "Functions marked `security definer` run as their owner and bypass RLS. Keep them out of the exposed schema, or check permissions inside them.",
              "Storage. Files in Supabase Storage have their own policies on `storage.objects`, and a public bucket is readable by anyone with a file's URL.",
              "The `service_role` key. If it's anywhere in your front-end code or a public repo, rotate it now: it bypasses every policy.",
            ],
          },
          {
            code: `create view public.my_orders
with (security_invoker = true) as
select * from public.orders;`,
            lang: "sql",
          },
        ],
      },
      {
        h2: "Step 4: test it like an attacker",
        blocks: [
          {
            p: "Run the request from earlier again, with the anon key and no user session. For a private table you should now get an empty array (or a `permission denied` error, if the table has no grant for `anon`), and an insert should fail. Then sign in as an ordinary user and confirm you can see your own rows and nobody else's. Finally, open the Security Advisor in the Supabase dashboard and check the warning has gone.",
          },
        ],
      },
      {
        h2: "When the tables aren't the only problem",
        blocks: [
          {
            p: "If an AI tool generated your app, open tables are rarely the only issue. The same apps tend to have secrets in client code, unchecked inputs and payment webhooks that trust the browser. If you'd rather have the whole app checked properly, that's what my app rescue audit covers.",
          },
        ],
      },
    ],
  },

  {
    slug: "fix-404-on-refresh-single-page-app",
    title: "Your app shows a 404 when you refresh the page: the fix for Vercel, Netlify, AWS and Nginx",
    seoTitle: "Fix the 404 on Refresh in a React or Lovable App · Sameem Amjad",
    seoDescription:
      "Every page but the homepage 404s on refresh after deploying a Vite, React or Lovable app? Here's why, and the exact fix for Vercel, Netlify, AWS and Nginx.",
    summary:
      "Why deep links break on single-page apps, and the one rewrite rule each host needs, plus the two side effects to handle.",
    published: "2026-09-29",
    updated: "2026-09-29",
    service: "fix-vibe-coded-app",
    sections: [
      {
        h2: "The short answer",
        blocks: [
          {
            p: "Your app is a single-page app. The server has one real page, `index.html`, and the app draws every other URL in the browser. Clicking a link works because the browser never asks the server. Refreshing `/dashboard` does ask the server, which looks for a file called `dashboard`, finds nothing and returns a 404. The fix is a rewrite that sends every path that isn't a real file to `index.html`.",
          },
        ],
      },
      {
        h2: "Which apps this applies to",
        blocks: [
          {
            p: "Any app rendered entirely in the browser: Vite and React with React Router, Create React App, and the Vite apps AI builders generate. Lovable projects created before it moved new projects to TanStack Start in 2026 are this kind of app, as are many Bolt projects. Frameworks that render pages on a server, such as Next.js, route on the server and don't have this problem. Newer Lovable projects run on TanStack Start, which also renders on a server: if one of those 404s after deploying, the cause is the deploy target rather than a missing rewrite, and this fix won't apply.",
          },
        ],
      },
      {
        h2: "Vercel",
        blocks: [
          { p: "Add a `vercel.json` at the root of the project:" },
          {
            code: `{
  "rewrites": [
    { "source": "/(.*)", "destination": "/index.html" }
  ]
}`,
            lang: "json",
          },
          {
            p: "Vercel serves real files first, so your JavaScript, CSS and images still load; the rewrite only applies when no file matches. If the project has serverless functions under `/api`, leave them out of the rewrite by using `/((?!api/).*)` as the source.",
          },
        ],
      },
      {
        h2: "Netlify",
        blocks: [
          { p: "Add a `_redirects` file to the folder that gets published (for a Vite app, put it in `public/`):" },
          { code: "/*    /index.html    200", lang: "text" },
          {
            p: "The `200` makes it a rewrite rather than a redirect, so the address bar keeps the URL the visitor asked for. Netlify also serves real files before applying the rule.",
          },
        ],
      },
      {
        h2: "AWS: S3 with CloudFront, or Amplify",
        blocks: [
          {
            p: "With S3 behind CloudFront, add custom error responses to the distribution for both 403 and 404 that return `/index.html` with a 200 status. You need both codes: S3 answers 403, not 404, for a missing file unless the requester has `s3:ListBucket` permission, which CloudFront's origin access and most public-read bucket policies don't grant.",
          },
          {
            p: "On AWS Amplify Hosting, add the single-page-app rewrite from Amplify's documentation under Rewrites and redirects. It sends everything to `/index.html` as a 200 rewrite except files with the extensions it lists, and Amplify doesn't check whether a file exists first, so add any other extension your build serves (for example `xml`, `webmanifest`, `jpeg`, `avif` or `pdf`) or those files will come back as your app.",
          },
        ],
      },
      {
        h2: "Nginx",
        blocks: [
          {
            code: `location / {
    try_files $uri $uri/ /index.html;
}`,
            lang: "nginx",
          },
          {
            p: "`try_files` serves the file if it exists, then a directory, and otherwise falls back to `index.html`.",
          },
        ],
      },
      {
        h2: "Two side effects to handle",
        blocks: [
          {
            list: [
              "Real 404s disappear. Every mistyped URL now returns your app with a 200 status, which search engines treat as a soft 404. Add a catch-all route in the app that shows a proper not-found page, and mark it `noindex`.",
              "Search engines still see a blank page. The rewrite fixes refreshes, not SEO: a crawler that doesn't run JavaScript gets the same empty `index.html` for every URL. If the app needs to rank, prerender each route to real HTML at build time. This site is a Vite and React app prerendered page by page, which is how every page here reaches search engines with its own title and content.",
            ],
          },
        ],
      },
      {
        h2: "If the 404 is the least of it",
        blocks: [
          {
            p: "A deploy that 404s is often the first sign of a wider production problem: environment variables missing on the host, login redirects pointing at the preview URL, or a database that's open to the public. If you'd like the whole app checked and fixed, that's what my app rescue service does.",
          },
        ],
      },
    ],
  },
];

export const getGuideBySlug = (slug) => guides.find((g) => g.slug === slug) || null;
